import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Script from 'next/script';

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <Script
                    src="https://cdn.mypersonas.ai/static/js/mypersonas.js"
                    data-integration-id="01KA976ZFKC1EQYH5K53AX33B2"
                    data-product=""
                    data-region="us"
                    defer
                    strategy="afterInteractive"
                />

                <Script id="user-details" strategy="afterInteractive">
                    {`
                        window.MYP_HOST_DETAILS = window.MYP_HOST_DETAILS || {};
                        window.MYP_HOST_DETAILS.user = {
                            providerUserId: "1234567890",
                            firstName: "John",
                            lastName: "Doe",
                            email: "john.doe@example.com",
                            provider: "Anand's Website"
                        };
                    `}
                </Script>
                {children}
            </body>
        </html>
    );
}
